
sealValidation.py::test_sealTest[7ef4386566f61eea604398f809f3672bqweDelimqwe1649227967qweDelimqweroot] FAILED

=================================== FAILURES ===================================
_ test_sealTest[7ef4386566f61eea604398f809f3672bqweDelimqwe1649227967qweDelimqweroot] _

seal = '7ef4386566f61eea604398f809f3672bqweDelimqwe1649227967qweDelimqweroot'

    @allure.title('Seal update test')
    def test_sealTest(seal):
>       debugEnable(int(debugLevel))
E       NameError: name 'debugLevel' is not defined

sealValidation.py:34: NameError
=========================== short test summary info ============================
FAILED sealValidation.py::test_sealTest[7ef4386566f61eea604398f809f3672bqweDelimqwe1649227967qweDelimqweroot]
============================== 1 failed in 0.17s ===============================
